packages:
  - apps/*
  - packages/*
verifyDepsBeforeRun: false
allowBuilds:
  sharp: true
  '@swc/core': true
  unrs-resolver: true
  esbuild: true
  workerd: true
minimumReleaseAgeExclude:
  - maplibre-gl@6.13.0
  - '@opennextjs/cloudflare@1.20.9'
  - miniflare@5.20261006.0-alpha
  - wrangler@4.148.0
