// Generated by apps/web/scripts/import-lot-photos.mjs. Do not edit by hand.
import type { MediaImage } from "@bba/contracts";

export const lotPhotos: Readonly<Record<number, readonly MediaImage[]>> = {
  "7601": [
    {
      "src": "/images/lots/7601-brisane-21/01.webp",
      "width": 2000,
      "height": 1333,
      "focalPoint": "40% 55%",
      "alt": {
        "fr": "Petit croiseur sur sa remorque",
        "en": "Small cruiser on its trailer"
      }
    },
    {
      "src": "/images/lots/7601-brisane-21/02.webp",
      "width": 1600,
      "height": 1067,
      "focalPoint": "45% 60%",
      "alt": {
        "fr": "Le voilier amarré au ponton",
        "en": "The sailboat moored at the pontoon"
      }
    },
    {
      "src": "/images/lots/7601-brisane-21/03.webp",
      "width": 2000,
      "height": 1500,
      "focalPoint": "50% 50%",
      "alt": {
        "fr": "La cuisine et les couchettes",
        "en": "Galley and berths"
      }
    }
  ],
  "7605": [
    {
      "src": "/images/lots/7605-noordmeer-6-7/01.webp",
      "width": 2000,
      "height": 1500,
      "focalPoint": "50% 60%",
      "alt": {
        "fr": "Sloep classique à coque crème, à terre",
        "en": "Classic cream-hulled sloep, ashore"
      }
    },
    {
      "src": "/images/lots/7605-noordmeer-6-7/02.webp",
      "width": 2000,
      "height": 1500,
      "focalPoint": "50% 60%",
      "alt": {
        "fr": "La sloep de trois quarts arrière",
        "en": "The sloep from the rear quarter"
      }
    },
    {
      "src": "/images/lots/7605-noordmeer-6-7/03.webp",
      "width": 2000,
      "height": 1500,
      "focalPoint": "50% 50%",
      "alt": {
        "fr": "La poupe et le liston en cordage",
        "en": "Stern and rope fender"
      }
    }
  ],
  "7610": [
    {
      "src": "/images/lots/7610-rumbelo-450/01.webp",
      "width": 1350,
      "height": 900,
      "focalPoint": "45% 60%",
      "alt": {
        "fr": "Petit bateau à moteur ouvert en navigation",
        "en": "Small open motorboat underway"
      }
    },
    {
      "src": "/images/lots/7610-rumbelo-450/02.webp",
      "width": 1350,
      "height": 900,
      "focalPoint": "45% 60%",
      "alt": {
        "fr": "Le bateau de profil, moteur hors-bord",
        "en": "Side view with its outboard"
      }
    },
    {
      "src": "/images/lots/7610-rumbelo-450/03.webp",
      "width": 1350,
      "height": 900,
      "focalPoint": "50% 55%",
      "alt": {
        "fr": "Le bateau de trois quarts arrière",
        "en": "Rear three-quarter view"
      }
    }
  ],
  "7701": [
    {
      "src": "/images/lots/7701-solenne-38/01.webp",
      "width": 1024,
      "height": 720,
      "focalPoint": "50% 55%",
      "alt": {
        "fr": "Voilier de croisière au mouillage",
        "en": "Cruising sailboat at anchor"
      }
    },
    {
      "src": "/images/lots/7701-solenne-38/02.webp",
      "width": 1080,
      "height": 720,
      "focalPoint": "50% 50%",
      "alt": {
        "fr": "Le pont et la capote, vus de l’avant",
        "en": "Deck and sprayhood seen from the bow"
      }
    },
    {
      "src": "/images/lots/7701-solenne-38/03.webp",
      "width": 960,
      "height": 720,
      "focalPoint": "50% 55%",
      "alt": {
        "fr": "Le carré et sa table",
        "en": "Saloon and table"
      }
    }
  ],
  "7702": [
    {
      "src": "/images/lots/7702-kerlys-31/01.webp",
      "width": 1920,
      "height": 1186,
      "focalPoint": "45% 60%",
      "alt": {
        "fr": "Voilier classique sous spinnaker",
        "en": "Classic sailboat under spinnaker"
      }
    },
    {
      "src": "/images/lots/7702-kerlys-31/02.webp",
      "width": 2000,
      "height": 1468,
      "focalPoint": "50% 45%",
      "alt": {
        "fr": "Voilier au mouillage dans une crique rocheuse",
        "en": "Sailboat moored in a rocky cove"
      }
    },
    {
      "src": "/images/lots/7702-kerlys-31/03.webp",
      "width": 1500,
      "height": 1001,
      "focalPoint": "50% 50%",
      "alt": {
        "fr": "Le carré boisé et ses banquettes bleues",
        "en": "Wooden saloon with blue settees"
      }
    }
  ],
  "7706": [
    {
      "src": "/images/lots/7706-pecheur-7-0/01.webp",
      "width": 1280,
      "height": 960,
      "focalPoint": "45% 65%",
      "alt": {
        "fr": "Bateau de pêche-promenade avec timonerie, à quai",
        "en": "Walkaround fishing boat with wheelhouse, alongside"
      }
    },
    {
      "src": "/images/lots/7706-pecheur-7-0/02.webp",
      "width": 1280,
      "height": 960,
      "focalPoint": "55% 55%",
      "alt": {
        "fr": "L’avant et le toit de la timonerie",
        "en": "Foredeck and wheelhouse roof"
      }
    },
    {
      "src": "/images/lots/7706-pecheur-7-0/03.webp",
      "width": 1280,
      "height": 960,
      "focalPoint": "60% 50%",
      "alt": {
        "fr": "Le poste de pilotage dans la timonerie",
        "en": "Helm station inside the wheelhouse"
      }
    }
  ],
  "7710": [
    {
      "src": "/images/lots/7710-calanque-750/01.webp",
      "width": 1600,
      "height": 1100,
      "focalPoint": "40% 60%",
      "alt": {
        "fr": "Semi-rigide en navigation près de la côte",
        "en": "RIB underway near the coast"
      }
    },
    {
      "src": "/images/lots/7710-calanque-750/02.webp",
      "width": 1600,
      "height": 1100,
      "focalPoint": "50% 55%",
      "alt": {
        "fr": "Le cockpit et le bain de soleil, au ponton",
        "en": "Cockpit and sun pad at the pontoon"
      }
    },
    {
      "src": "/images/lots/7710-calanque-750/03.webp",
      "width": 2000,
      "height": 1100,
      "focalPoint": "45% 60%",
      "alt": {
        "fr": "La banquette et la table du cockpit",
        "en": "Cockpit seating and table"
      }
    }
  ],
  "7712": [
    {
      "src": "/images/lots/7712-alize-40/01.webp",
      "width": 1600,
      "height": 1200,
      "focalPoint": "50% 60%",
      "alt": {
        "fr": "Catamaran de croisière dans une baie",
        "en": "Cruising catamaran in a bay"
      }
    },
    {
      "src": "/images/lots/7712-alize-40/02.webp",
      "width": 1440,
      "height": 1920,
      "focalPoint": "50% 72%",
      "alt": {
        "fr": "Catamaran au mouillage devant la plage",
        "en": "Catamaran at anchor off the beach"
      }
    },
    {
      "src": "/images/lots/7712-alize-40/03.webp",
      "width": 1440,
      "height": 1920,
      "focalPoint": "50% 60%",
      "alt": {
        "fr": "Le carré et la cuisine",
        "en": "Saloon and galley"
      }
    }
  ]
};
